services:
  postgres:
    image: postgres:15
    container_name: flashbook_postgres
    environment:
      POSTGRES_USER: flashbook
      POSTGRES_PASSWORD: flashbook
      POSTGRES_DB: flashbook
    ports:
      - "5544:5432"
    volumes:
      - flashbook_pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U flashbook -d flashbook"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7
    container_name: flashbook_redis
    ports:
      - "6380:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  flashbook_pg_data:
