ALTER TABLE seats ADD COLUMN seat_type VARCHAR(20) NOT NULL DEFAULT 'standard';
ALTER TABLE seats ADD COLUMN row_num INT NOT NULL DEFAULT 1;
ALTER TABLE seats ADD COLUMN col_num INT NOT NULL DEFAULT 1;
